language: node_js
node_js:
- 6.11.2
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install: yarn install
script: yarn run test
deploy:
  provider: npm
  email: npmjs+eng@eventbrite.com
  api_key: uq42PrHFNPf8CGRmilDdep5cOVynutOV8BImHH0/2O68Zce3GE/hFP+yJj8Ba2uO2Vjvs5wcNUQKrb4/zWNcHYpbeb/8dvNpsFFL3Of7+/CcvF3DG+LomRF+4AFigjwmHYSmJzLr94+/RN8nn1SZsUIUOY2xXHq5PDFVVlGvTtgxBxemLGZg9sO/vy6Teg58bl9Fv9DAAGNK8X9BpNAOEUgX2DolUKXVmB8DZ2WM6UHWiJzUYaJmeLG3fR+oCydzdvZnPfa9JCoR20bIk+FBC0VLelVHTh4WnD2cVQbx9m8Ip74JYZ2Id3rrkqT1zcf3S2BSRuFolR5b4O0HIF/OFCmfAukuXiFJQSOQRpIPjnG21vv74F5dD48HyRZy+Z58EQsnaTo6cHVg+RpjflDs0VVsY/MTF0RnHdespaJGgd5AfTAjGPWKUNKhTDZW1bLboj/L3bz+d68N2lkW29B5JKGPw1t4rLC39ooP3uXvv4CtvmIPaJmHTfRIUj1blXbXroNT7wWXWfjrP1vgaMu0GUhWtLBtGMAW9wCTtF3cndbWw7isoMo/Zdi2OcuLu8eZAiWhXxeBd9R3oFOkswO/84q9EJSjJ1KAQm4E+Nx7Yy50CXCq6gRHoNrLPtL/MheYaQpt270dIAFjCR3RkCa/QnaeVB3qoZmfwEwcJ2UY1vw=
  on:
    tags: true
    repo: eventbrite/britecharts-react
