language: node_js
node_js:
- 6.11.2
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  - provider: npm
    script: yarn run build
    skip_cleanup: true
    email: npmjs+eng@eventbrite.com
    api_key:
      secure: $BRITECHARTS_REACT_TRAVIS_KEY
    on:
      tags: true
      repo: eventbrite/britecharts-react
  - provider: pages
    script: rm .gitignore && yarn run docs
    skip_cleanup: true
    github_token: $GITHUB_JAYLUM_CHEN
    on:
      tags: true
