language: node_js
node_js:
- 6.11.2
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
# cache: yarn
# install: yarn install
# script: yarn run test
# after_success: git remote add origin-pages https://${GITHUB_JAYLUM_CHEN}@github.com/eventbrite/britecharts-react.git > /dev/null 2>&1 && git rm .gitignore && git rm -r --ignore-unmatch `ls | grep -v package.json` && git add . && git commit -m 'testing' && git push -fu origin-pages HEAD:test12345
before_deploy: yarn run docs && yarn run build
deploy:
  - provider: npm
    skip_cleanup: true
    email: npmjs+eng@eventbrite.com
    api_key:
      secure: $BRITECHARTS_REACT_TRAVIS_KEY
    on:
      tags: true
      repo: eventbrite/britecharts-react
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_JAYLUM_CHEN
