language: node_js
node_js:
- 6.11.2
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_deploy: yarn run build && yarn run docs
deploy:
  - provider: npm
    skip_cleanup: true
    email: npmjs+eng@eventbrite.com
    api_key:
      secure: $BRITECHARTS_REACT_TRAVIS_KEY
    on:
      tags: true
      repo: eventbrite/britecharts-react
after_deploy: git remote add origin-pages https://${GITHUB_JAYLUM_CHEN}@github.com/eventbrite/britecharts-react.git > /dev/null 2>&1 && git rm .gitignore && git rm -r --ignore-unmatch `ls | grep -v docs` && git add . && git commit -m 'testing' && git push -fu origin-pages HEAD:gh-pages
